# Generated by Django 2.1.1 on 2018-10-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
