# Generated by Django 2.1.1 on 2018-10-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_staffmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmembers',
            name='storeid',
        ),
        migrations.RemoveField(
            model_name='staffmembers',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffMembers',
        ),
    ]
