# Generated by Django 2.1.1 on 2018-10-11 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0007_auto_20181011_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeid', models.ForeignKey(blank=True, db_column='StoreID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='testApp.Stores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
